<a href="https://colab.research.google.com/github/Neamalinga/NUMPY-ASSIGNMENT/blob/main/NUMPY_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.How do you import the NumPy library using an alias?
import numpy as np

In [ ]:
#2.How do you check the version and configuration of NumPy?
np.__version__

'2.0.2'

In [ ]:
#3.How do you create a vector filled with zeros of size 10?
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# To find help/documentation for a NumPy function, you can use np.info() or np.lookfor()
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

In [ ]:
#5.How do you create a zero vector of size 10 with the fifth element as 1?
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#6.How do you create a vector with values from 10 to 49?
a=np.arange(10,49)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#7.How do you reverse a vector?
a=np.arange(10,49)
a[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [ ]:
#8.How do you create a 3x3 matrix with values from 0 to 8?
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#9.How do you find indices of non-zero elements in an array?
a=np.array([1,2,0,7,0,0])
print(np.nonzero(a))

(array([0, 1, 3]),)


In [ ]:
#10.How do you create a 3x3 identity matrix?
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#11.How do you generate a 3x3x3 array with random values?
np.random.rand(3,3,3)

array([[[0.28507454, 0.74179465, 0.98777787],
        [0.15397698, 0.24430372, 0.20509102],
        [0.36830358, 0.59214134, 0.17714014]],

       [[0.12237898, 0.2924724 , 0.84685855],
        [0.62870842, 0.22829537, 0.07336161],
        [0.1605749 , 0.70683435, 0.74529774]],

       [[0.60788957, 0.41809932, 0.79969789],
        [0.48737435, 0.01056478, 0.22907127],
        [0.53696104, 0.8224626 , 0.6740727 ]]])

In [ ]:
#12.How do you find the min and max values in a 10x10 random matrix?
a=np.random.rand(10,10)
print(a.min())
print(a.max())

0.009556385575400506
0.9984608870436349


In [ ]:
#13.How do you calculate the mean of a random vector of size 30?
np.random.rand(30)
np.mean(np.random.rand(30))

np.float64(0.5790184988614094)

In [ ]:
#14.How do you create a 2D array with 1s on the border and 0s inside?
# Create a 5x5 array of ones
a = np.ones((5, 5))

# Set the inner part to zeros using slicing
a[1:-1, 1:-1] = 0

print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#15.What is the result of operations like 0 * np.nan, np.nan == np.nan, etc.?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [ ]:
#16.How do you create a matrix with values below the diagonal?
import numpy as np
arr=np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
#17.How do you create a checkerboard pattern in an 8x8 matrix?
import numpy as np

# Create an 8x8 matrix
checkerboard = np.zeros((8, 8), dtype=int)

# Use slicing to set alternating values
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#20.How do you normalize a matrix (values between 0 and 1)?
import numpy as np

#creating a matrix (5*5)with random values
 matrix = np.random.rand(5, 5) * 100
min_value = matrix.min()
max_value = matrix.max()

Normalized_matrix = (matrix-min_value)/(max_value-min_value)
print(Normalized_matrix)

[[0.96510139 0.35232789 0.88555937 0.35699346 0.93310307]
 [0.95208836 0.15447334 0.0359477  0.28264983 0.23629856]
 [0.99160611 0.13749921 0.74523435 1.         0.        ]
 [0.78346537 0.7507472  0.27017265 0.63995206 0.2176883 ]
 [0.89140984 0.69331004 0.10836022 0.76573706 0.40852098]]


In [ ]:
#21.How do you define a custom data type for storing color (RGBA)?
import numpy as np

# Define a custom data type for RGBA color
# 'u1' is an unsigned 8-bit integer, suitable for color values (0-255)
color_dtype = np.dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

# You can now create arrays using this custom data type
# For example, creating an array of one RGBA color
rgba_color = np.array([(255, 0, 0, 255)], dtype=color_dtype)
print(rgba_color)

# Creating an array of multiple RGBA colors
rgba_colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
print(rgba_colors)

[(255, 0, 0, 255)]
[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


In [ ]:
#22.How do you perform a matrix multiplication between two matrices?
import numpy as np

# Create two sample matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result=matrix1@matrix2
print(result)

[[19 22]
 [43 50]]


In [ ]:
#23.How do you negate values between two given numbers in a vector?
#import numpy as np
vector=np.array([1,2,3,4,7,9,3,11,13])
lower_bound=3
upper_bound=7


res = np.array([eval('-'+str(i)) for i in vector if i>=lower_bound and i<=upper_bound])
print(res)

[-3 -4 -7 -3]


In [ ]:
#24.What is the output of sum(range(5), -1) vs np.sum(range(5), -1)?
import numpy as np


python_sum = sum(range(5), -1)
print(f"Output of sum(range(5), -1): {python_sum}"
numpy_sum = np.sum(np.arange(5), -1)
print(f"Output of np.sum(np.arange(5), -1): {numpy_sum}")

Output of sum(range(5), -1): 9
Output of np.sum(np.arange(5), -1): 10


In [ ]:
#25.Which NumPy vector operations are legal or illegal?
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
#26.What happens when you divide integers or floats by zero in NumPy?
a=np.array([1,2,3,4])
b=np.array([1.2,2.4,3.5,6.7])
print(a/0)
print(b/0)

[inf inf inf inf]
[inf inf inf inf]


/tmp/ipython-input-3920522152.py:4: RuntimeWarning: divide by zero encountered in divide
  print(a/0)
/tmp/ipython-input-3920522152.py:5: RuntimeWarning: divide by zero encountered in divide
  print(b/0)


In [ ]:
#27.How do you round a float array away from zero?
import numpy as np

# Create a sample float array
a = np.array([-1.2, 2.4, -1.7, -7.8, 5.6
rounded_away_from_zero = np.copysign(np.ceil(np.abs(a)), a)
print("Original array:")
print(a)
print("\nArray rounded away from zero:")
print(rounded_away_from_zero)

Original array:
[-1.2  2.4 -1.7 -7.8  5.6]

Array rounded away from zero:
[-2.  3. -2. -8.  6.]


In [ ]:
#28.How do you extract the integer part of a float using multiple methods?
a=np.array([-1.2,2.4,4.5,-2.3,3.4])
print(np.floor(a))



[-2.  2.  4. -3.  3.]


In [ ]:
#29.How do you create a 5x5 matrix with row values ranging from 0 to 4?
import numpy as np
matrix=np.tile(np.arange(0,5),(5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#30.How do you use a generator to create a NumPy array?


In [ ]:
#30.How do you use a generator to create a NumPy array?
import numpy as np

# Define a generator function
def my_generator():
    for i in range(10):
        yield(i)

# Create a NumPy array from the generator
# Note: You need to specify the dtype if the generator yields different types
arr_from_generator = np.fromiter(my_generator(), dtype=int)

print(arr_from_generator)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#31.How do you create an array with evenly spaced values between 0 and 1 (excluded)?
import numpy as np

# Create an array of 10 evenly spaced values between 0 and 1, excluding 1
# np.linspace(start, stop, num, endpoint=True)
# By setting endpoint=False, we exclude the stop value (1)
arr = np.linspace(0, 1, 10, endpoint=False)

print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
#32.How do you sort a random array?
import numpy as np

# Create a random array
random_array = np.random.rand(10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)
print(sorted_array)


[0.04858178 0.06503899 0.13676343 0.395126   0.41565249 0.42886246
 0.53261839 0.6174216  0.83756262 0.91792414]


In [ ]:
#34.How do you check if two arrays are equal?
import numpy as np

# Create two sample arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([1, 2, 3, 4])

# Check if the arrays are equal
are_equal = np.array_equal(array1, array2)

print(are_equal)


True


In [ ]:
#35.How do you make a numpy array read only?
import numpy as np

# Create a sample NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Make the array read-only
arr.flags.writeable = False


In [ ]:
#36.How do you convert Cartesian coordinates to polar coordinates?
import numpy as np

# Sample Cartesian coordinates (x, y)
x = np.array([1, 3, -2])
y = np.array([1, -3, 2])
#convert it into polar coordinates
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print("r=",r)
print("theta=",theta)




r= [1.41421356 4.24264069 2.82842712]
theta= [ 0.78539816 -0.78539816  2.35619449]


In [ ]:
#37.How do you replace the maximum value in an array with zero?
import numpy as np

# Create a sample array
a = np.arange(10)
max_index = np.argmax(a)
a[max_index] = 0
print(a)

[0 1 2 3 4 5 6 7 8 0]


In [ ]:
#38.How do you create a structured array for (x, y) coordinate pairs?
import numpy as np
dtype=[('x',float),('y',float)]
arr=np.array([(1,2),(3,4)],dtype=dtype)
print(arr)





[(1., 2.) (3., 4.)]


In [ ]:
import numpy as np

# Define two arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Create the Cauchy matrix

cauchy_matrix = 1.0/x[:,None]+y[None,:]

print(cauchy_matrix)

[[5.         6.         7.        ]
 [4.5        5.5        6.5       ]
 [4.33333333 5.33333333 6.33333333]]


In [ ]:
#40.How do you find the range of values for each NumPy scalar type?
import numpy as np
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))



Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------



In [ ]:
#41.How do you display all values in a large array?
import numpy as np
arr=np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
#42.How do you find the closest value to a given scalar in an array?
import numpy as np
arr=np.array([3,7,10,15,20])
scalar=12
closest_value=arr[np.abs(arr-scalar).argmin()]
print(closest_value)



10


In [ ]:
#43.How do you create a structured array with position and color fields?
dtype=[('position', [('x', float), ('y', float)]), ('color', [('r', 'U10'), ('g', 'U10'), ('b', 'U10')])]
data=np.array([((1.0,2.0),'red'),((3.5,4.2),'blue'),((2.9,1.2),'green')],dtype=dtype)
print("positions:/n",data['position'])
print("colors:/n",data['color'])


positions:/n [(1. , 2. ) (3.5, 4.2) (2.9, 1.2)]
colors:/n [('red', 'red', 'red') ('blue', 'blue', 'blue')
 ('green', 'green', 'green')]


In [ ]:
#44.How do you compute pairwise distances between coordinates?
points=np.array([(1,2),(3,4),(5,6)])

distances = np.sqrt(((points[:,None,:] - points[None,:,:])**2).sum(axis=-1))

print(distances)

[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [ ]:
#how do you cast a float array to integer type in place?
import numpy as np
arr=np.array([1.2,3.4,5.6,7.8])
arr=arr.astype(int)
print(arr)



[1 3 5 7]


In [ ]:
#47.How do you iterate through all elements in a NumPy array with indices?
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
for index,value in np.ndenumerate(a):
    print(index,value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9


In [ ]:
#49.How do you randomly place a specific number of elements in a 2D array?
import numpy as np
a=np.array([(1,2),(3,4)])
a[0,1]


np.int64(2)

In [ ]:
#50.How do you subtract the row mean from a matrix?
import numpy as np
a=np.array([(1,2),(3,4)])
row_mean=np.mean(a,axis=1)
print(row_mean)
print(a-row_mean)

[1.5 3.5]
[[-0.5 -1.5]
 [ 1.5  0.5]]


In [ ]:
##51.How do you sort a 2D array based on the values of one column?

import numpy as np

# Create a sample 2D array
a = np.array([[3, 2], [1, 4], [2, 1]])

# Sort the array based on the values of the first column (index 0)
sorted_array = a[a[:, 0].argsort()]

print(sorted_array)

[[1 4]
 [2 1]
 [3 2]]


In [ ]:
#52.How do you check if a 2D array contains any null (zero-only) columns?
import numpy as np
a=np.array([[0,1,2],
            [0,2,0],
            [0,3,0]])
zero_columns=np.all(a==0,axis=0)
print(zero_columns)

[ True False False]


In [ ]:
#53.How do you find the nearest value to a given number in a NumPy array?
import numpy as np
arr=np.array([1.2,2.3,4.5,5.2,6.7])
given_number=2.5
nearest_value=arr[np.abs(arr-given_number).argmin()]
print(nearest_value)

2.3


In [ ]:
#55.How do you increment elements in an array using an index array with repeats?
import numpy as np
arr=np.zeros(5,dtype=int)
indices=np.array([0,1,2,3,4])
np.add.at(arr,indices,1)
print(arr)


[1 1 1 1 1]


In [ ]:
#56.How do you accumulate values into an array based on indices?
import numpy as np
values=np.array([5,4,3,2,1])
indices=np.array([4,0,1,2,3])
arr=np.zeros(5,dtype=int)
np.add.at(arr,indices,values)
print(arr)

[4 3 2 1 5]


In [ ]:
#57.How do you count unique colors in a 3D image array?
import numpy as np
image=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
unique_colors=np.unique(image)
print(unique_colors)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#58.How do you compute the sum across the last two axes of a 4D array?
import numpy as np
a=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

print(a.sum(axis=(2,3)))

[[21 57]]


In [ ]:
#59.How do you calculate means of grouped values in an array?
groups=np.array([0,1,1,0,2,2,1])
values=np.array([10,20,25,30,5,15,35])
sums=np.bincount(groups,weights=values)
counts=np.bincount(groups)
means=sums/counts
print(means)



[20.         26.66666667 10.        ]


In [ ]:
#60.How do you efficiently get the diagonal of a matrix dot product?
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
product=np.dot(a,b)
diag=np.diagonal(product)
print(diag)




[19 50]


In [ ]:
#62.How do you multiply a (5,5,3) array with a (5,5) array element-wise?
a=np.random.rand(5,5,3)

b=np.random.rand(5,5)
result=(a*b[:,:,np.newaxis])
print(result.shape)

(5, 5, 3)


In [ ]:
#63.How do you swap two rows in a matrix?
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[[0,1]]=a[[1,0]]
print(a)


[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [ ]:
#64.How do you extract unique line segments from triangle definitions?
import numpy as np
triangles=np.array([[0,1,2],
                    [2,3,0]])
edges=np.concatenate([triangles[:,[0,1]],
                      triangles[:,[1,2]],
                      triangles[:,[2,0]]])
edges=np.sort(edges,axis=1)
unique_edges=np.unique(edges,axis=0)
print(unique_edges)





[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [2 3]]


In [ ]:
#65.How do you recreate an array from a bincount?
import numpy as np
x=np.array([1,2,3,4,5])
y=np.bincount(x)
values = np.arange(len(y))
recreated_array = np.repeat(values, y)
print(recreated_array)

[1 2 3 4 5]


In [ ]:
#66.How do you compute a moving average using a sliding window?
a=np.arange(10)
window=4
moving_sum=np.convolve(a,np.ones(window)/window,'valid')
moving_average=moving_sum/window
print(moving_average)




[0.375 0.625 0.875 1.125 1.375 1.625 1.875]


In [ ]:
#67.How do you create a rolling 2D view from a 1D array?
import numpy as np

# Create a 1D array
arr = np.arange(10)
window_size = 3
itemsize = arr.itemsize
stride = arr.strides[0]
rolling_view = np.lib.stride_tricks.as_strided(arr, shape=(len(arr) - window_size + 1, window_size), strides=(stride, itemsize))
print(rolling_view)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:

#68.How do you invert booleans or negate floats in-place?
import numpy as np
x=np.array([False,True,True,False])
x[:]=~x
print(x)


[ True False False  True]


In [ ]:
#71.How do you extract a fixed-shaped subarray centered on a given point?
import numpy as np
a=np.arange(25).reshape(5,5)
center_point=(1,2)
half_size=1
r,c=center_point
subarray=a[r-half_size:r+half_size+1,c-half_size:c+half_size+1]
print(subarray)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
#72.How do you generate overlapping subarrays from a vector?
import numpy as np

# Create a 1D array
arr = np.arange(10)
subarray_size = 3
step_size = 1
itemsize = arr.itemsize
stride = arr.strides[0]
rolling_view = np.lib.stride_tricks.as_strided(arr, shape=((len(arr) - subarray_size) // step_size + 1, subarray_size), strides=(step_size * stride, itemsize))
print(rolling_view)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#73.How do you compute the rank of a matrix using SVD?
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
U, s, V = np.linalg.svd(matrix)
rank = np.sum(s > 1e-10)
print("Original Matrix:")
print(matrix)
print("\nSingular Values:")
print(s)
print("\nRank of the matrix:", rank)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Singular Values:
[1.68481034e+01 1.06836951e+00 4.41842475e-16]

Rank of the matrix: 2


In [ ]:
#74.How do you find the most frequent value in an array?
import numpy as np

# Create a sample array
arr = np.array([1, 2, 3, 2, 1, 2, 3, 4, 5, 4, 4, 4])
counts = np.bincount(arr)
most_frequent_value = np.argmax(counts)
print("Most frequent value:", most_frequent_value)

Most frequent value: 4


In [ ]:
#75.How do you extract all 3x3 contiguous blocks from a 10x10 matrix?
a=np.arange(100).reshape(10,10)
blocks=np.lib.stride_tricks.sliding_window_view(a,(3,3))
print(blocks[0,0])


[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [ ]:
#76.How do you create a 2D symmetric matrix class?
a=np.random.randint(1,10,(4,4))
symmetric_matrix=(a+a.T)/2
print(symmetric_matrix)

[[6.  4.  4.  5.5]
 [4.  2.  4.5 4.5]
 [4.  4.5 2.  3. ]
 [5.5 4.5 3.  1. ]]


In [ ]:
#77.How do you compute the sum of multiple matrix-vector products at once?

import numpy as np
matrices=np.random.randint(1,10,(3,3,3))
vectors=np.random.randint(1,10,(3,3))
result=np.zeros(3)
for A,x in zip(matrices,vectors):
    result+=A @ x
print(result)

[211. 158. 117.]


In [ ]:
#78.How do you compute the sum of blocks in a 2D array?
import numpy as np

# Create a sample 2D array
array = np.arange(36).reshape(6, 6)
block_shape = (3, 3)
blocks = np.lib.stride_tricks.sliding_window_view(array, block_shape)
sum_of_blocks = blocks.sum(axis=(-2, -1))
print("\nSum of Blocks:")
print(sum_of_blocks)


Sum of Blocks:
[[ 63  72  81  90]
 [117 126 135 144]
 [171 180 189 198]
 [225 234 243 252]]


In [ ]:
#80.How do you extract the top N largest values from an array?
import numpy as np
arr=np.array([10,5,8,12,3,7])
n=3
largest_values=arr[np.argsort(arr)[-n:]]
print(largest_values)



[ 8 10 12]


In [ ]:
#81.How do you create a Cartesian product of multiple input arrays?
import numpy as np
from itertools import product

a=np.array([1,2])
b=np.array([3,4])
c=np.array([5,6])
cartesian_product=np.array(list(product(a,b,c)))
print(cartesian_product)

[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


In [ ]:
#82.How do you create a record array from a regular NumPy array?
import numpy as np

# Create a regular NumPy array
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 22)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])
record_array = np.rec.array(regular_array)
print(record_array)

[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 22)]


In [ ]:
#83.How do you raise an array to the power of 3 using different methods?
import numpy as np

# Create a sample NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Method 1: Using the ** operator
result_operator = arr ** 3
print("Using the ** operator:", result_operator)

# Method 2: Using np.power()
result_power = np.power(arr, 3)
print("Using np.power():", result_power)

# Method 3: Using element-wise multiplication
result_multiplication = arr * arr * arr
print("Using element-wise multiplication:", result_multiplication)

Using the ** operator: [  1   8  27  64 125]
Using np.power(): [  1   8  27  64 125]
Using element-wise multiplication: [  1   8  27  64 125]


In [ ]:
#84.How do you find rows in a matrix containing all elements of another matrix?
import numpy as np
A=np.array([[1,2,3,4],
            [4,5,6,7],
            [2,3,4,5],
            [7,8,9,1]])
B=np.array([2,3,4,5])
contains_elements = np.isin(A, B)
rows_containing_all_elements = np.all(contains_elements, axis=1)
result_rows = A[rows_containing_all_elements]
print(result_rows)

[[2 3 4 5]]


In [ ]:
#85.How do you filter rows in a matrix with at least one differing value?
a=np.array([[1,2,3],
            [1,2,3],
            [4,5,6],
            [1,2,4]])
ref=np.array([1,2,3])
mask=np.any(a!=ref,axis=1)
filtered_rows=a[mask]
print(filtered_rows)




[[4 5 6]
 [1 2 4]]


In [ ]:
#86.How do you convert integers to their binary matrix representation?
import numpy as np
arr=np.array([1,2,3],dtype=np.uint8)
binary_matrix=np.unpackbits(arr[:,np.newaxis],axis=1)
print(binary_matrix)


[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]]


In [ ]:
#87.How do you extract unique rows from a 2D array?
a=np.array([[1,2,3],
            [1,2,3],
            [4,5,6],
            [1,2,4]])
unique_rows=np.unique(a,axis=0)
print(unique_rows)


[[1 2 3]
 [1 2 4]
 [4 5 6]]


In [ ]:
#88.How do you compute inner, outer, sum, and multiplication using einsum?
a=np.array([1,2,3])
b=np.array([4,5,6])
inner=np.einsum('i,i->',a,b)
outer=np.einsum('i,j->ij',a,b)
sum=np.einsum('i->',a)
multiplication=np.einsum('i,i->i',a,b)
print("inner",inner)
print("outer",outer)
print("sum",sum)
print("multiplication",multiplication)





inner 32
outer [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
sum 6
multiplication [ 4 10 18]


In [ ]:
#90.How do you filter 2D array rows that sum to a specific number using only integers?
import numpy as np
arr=np.array([[1,2,3],
              [4,1,1],
              [2,2,2],
              [3,3,0]],dtype=int)
specific_sum=6
rows_sum=np.sum(arr,axis=1)
filtered_rows=arr[rows_sum==specific_sum]
print(filtered_rows)

[[1 2 3]
 [4 1 1]
 [2 2 2]
 [3 3 0]]
